name: flutter_template

environment:
    sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
    melos: ^6.2.0

dependency_overrides:
    go_focus_mixin:
        path: packages/go_focus_mixin
    go_route_watcher:
        path: packages/go_route_watcher
    infinite_scroll_mixin:
        path: packages/infinite_scroll_mixin
    scroll_to_top_mixin:
        path: packages/scroll_to_top_mixin
    log_execution_time:
        path: packages/log_execution_time