name: infinite_scroll_mixin
description: "A mixin for Flutter that adds infinite scroll functionality to a ListView."
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

resolution: workspace