name: PR 코드 리뷰

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
      - name: 코드 리뷰 실행
        env:
          PPLX_API_KEY: ${{ secrets.PPLX_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/review_script.py
